### ISSUE TITLE
‘MouseData’ in namespace ‘xwin’ does not name a type; did you mean ‘TouchData’?

### ISSUE THREAD

**Issue by ognjenMarinkovic27** [alaingalvan/CrossWindow#15]
I think the example code should be changed, since it looks like MouseData does not exist. The only things I've found are MouseRawData and MouseMoveData.

**Comment by alaingalvan** [comment]
Thanks for letting me know about this, I've gone ahead and fixed that in the `readme.md` file and I'll take another pass through on the [demos repo](https://github.com/alaingalvan/crosswindow-demos) to be sure this has been revised.
